FROM elixir:1.15-alpine AS builder
WORKDIR /app
RUN mix local.hex --force && mix local.rebar --force
ENV MIX_ENV=prod
COPY mix.exs mix.lock ./
RUN mix deps.get --only prod && mix deps.compile
COPY . .
RUN mix release

FROM alpine:3.19
RUN apk --no-cache add libstdc++ openssl ncurses-libs
WORKDIR /app
COPY --from=builder /app/_build/prod/rel/<%= packageName %> .
<% if (transport === 'sse') { %>
EXPOSE 3000
<% } %>
CMD ["bin/<%= packageName %>", "start"]
